# Memcached settings

development:
  servers:
    - int-cons-vapp01.rnd.laxino.com:11211
    - int-cons-vapp01.rnd.laxino.com:11212
  expires: 20
  namespace: s3_dev
  no_block: false
  timeout: 30

test:
  servers:
    - dev-cons-app01.rnd.laxino.com:11211
  expires: 86400
  namespace: s3_tst
  no_block: true
  timeout: 30

integration0:
  servers:
    - int-cons-vapp01.rnd.laxino.com:11211
    - int-cons-vapp01.rnd.laxino.com:11212
  expires: 86400
  namespace: s3_int
  no_block: true
  timeout: 30

staging0: &staging0
  servers:
    - stg-cons-vapp01.rnd.laxino.com:11211
    - stg-cons-vapp01.rnd.laxino.com:11212
  expires: 86400
  namespace: s3_stg
  no_block: false
  timeout: 30

staging0_external:
  <<: *staging0
  namespace: s3_stg_ex

sandbox0:
  servers:
    - snd-cons-vapp01.sandbox.laxigames.com:11211
  expires: 86400
  namespace: s3_snd
  no_block: true
  timeout: 30

sandbox2:
  servers:
    - snd-cons-vapp01.sbox.so.idc02.laxigames.local:11211
  expires: 86400
  namespace: s3_snd
  no_block: true
  timeout: 30

smartocean2:
  servers:
    - prd-s3-vapp01.prod.so.idc02.laxigames.local:7000
    - prd-s3-vapp01.prod.so.idc02.laxigames.local:7001
    - prd-s3-vapp02.prod.so.idc02.laxigames.local:7000
    - prd-s3-vapp02.prod.so.idc02.laxigames.local:7001
  expires: 86400
  namespace: s3_prd
  no_block: true
  timeout: 15

production0:
  servers:
    - prd-s3-vapp01.prod.laxigames.com:7000
    - prd-s3-vapp01.prod.laxigames.com:7001
    - prd-s3-vapp02.prod.laxigames.com:7000
    - prd-s3-vapp02.prod.laxigames.com:7001
  expires: 86400
  namespace: s3_prd
  #no_block: true
  timeout: 15

mockup0:
  servers:
    - mo-mock-s3-vapp01.rnd.laxino.com:11211
    - mo-mock-s3-vapp01.rnd.laxino.com:11212
  expires: 3600
  namespace: s3_mock
  no_block: false
  timeout: 30

sandbox3:
  servers:
    - mo-snd-s3-vapp01.laxigames.local:11211
    - mo-snd-s3-vapp02.laxigames.local:11212
  expires: 86400
  namespace: s3_snd
  no_block: true
  timeout: 30

production3:
  servers:
    - mo-prd-s3-vapp01.laxigames.local:7000
    - mo-prd-s3-vapp01.laxigames.local:7001
    - mo-prd-s3-vapp02.laxigames.local:7000
    - mo-prd-s3-vapp02.laxigames.local:7001
  expires: 86400
  namespace: s3_prd
  no_block: true
  timeout: 30
